name: release_pypi

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Type of release: draft or release (default draft)'
        required: true
        default: 'draft'
        type: choice
        options:
          - draft
          - release

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          python -m pip install --upgrade pip
          # setuptools and build to build release
          pip install setuptools
          pip install build
          # twine to upload to pypi
          pip install twine

      - name: Build release
        if: github.ref == 'refs/heads/master'
        run: |
          echo "========================================================="
          echo "Building release files"
          python -m build --sdist --wheel
          echo "Contents of dist directory:"
          ls -lst dist
          echo "========================================================="

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to_testpypi:
    needs: build
    name: >-
      Publish to testpypi
    runs-on: ubuntu-latest
    if: github.event.inputs.release_type == 'draft'
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyspedas  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/

  publish-to_pypi:
    needs: build
    name: >-
      Publish to pypi
    runs-on: ubuntu-latest
    if: github.event.inputs.release_type == 'release'
    environment:
      name: pypi
      url: https://pypi.org/p/pyspedas  # Replace <package-name> with your PyPI project name
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
    - name: Download all the dists
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1

